In [1]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [6]:
import pandas as pd
import numpy as np

In [12]:
df = pd.DataFrame([[8,8,4],[7,9,5],[6,10,6],[5,12,7]],columns=['cgpa','profile_score','lpa'])
df

cgpa  profile_score  lpa
0     8              8    4
1     7              9    5
2     6             10    6
3     5             12    7

In [2]:
model = Sequential()

model.add(Dense(2,activation='linear',input_dim=2))
model.add(Dense(1,activation='linear'))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [3]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 2)              │             6 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │             3 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 9 (36.00 B)

 Trainable params: 9 (36.00 B)

 Non-trainable params: 0 (0.00 B)

In [4]:
model.get_weights()

[array([[-1.1305611,  0.6383157],
        [ 0.3984369, -0.114663 ]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[ 1.0308393],
        [-0.5966156]], dtype=float32),
 array([0.], dtype=float32)]

In [7]:
new_weights = [np.array([[0.1,0.1],
                         [0.1,0.1]],dtype=np.float32),
               np.array([0.,0.],dtype=np.float32),
               np.array([[0.1],
                         [0.1]],dtype=np.float32),
               np.array([0.],dtype=np.float32)]

In [8]:
model.set_weights(new_weights)

In [9]:
model.get_weights()

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.], dtype=float32)]

In [10]:
optimizer = keras.optimizers.Adam(learning_rate=0.001)
model.compile(loss="mean_squared_error",optimizer=optimizer)

In [13]:
model.fit(df.iloc[:,0:-1].values,df['lpa'].values,epochs=75,verbose=1,batch_size=1)

Epoch 1/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 34.2436 
Epoch 2/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 24.1348
Epoch 3/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 22.1292
Epoch 4/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 28.5674
Epoch 5/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 26.8543
Epoch 6/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 25.0509
Epoch 7/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 22.4700 
Epoch 8/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 23.3342 
Epoch 9/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 19.4286 
Epoch 10/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 26.2498 
Epoch 11/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 19.6831 
Epoch 12/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 26.9435
Epoch 13/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 28.2158 
Epoch 14/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 19.0604
Epoch 15/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 22.7817 
Epoch 16/75
4/4 

In [14]:
model.get_weights()

[array([[0.373854  , 0.373854  ],
        [0.36569428, 0.36569428]], dtype=float32),
 array([0.27246457, 0.27246457], dtype=float32),
 array([[0.37306598],
        [0.37306598]], dtype=float32),
 array([0.20480992], dtype=float32)]